services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - '5444:5432'
        volumes:
            - ./postgres/:/docker-entrypoint-initdb.d/

volumes:
    db:
